openapi: 3.0.0
info:
  title: APIM Test GCF API
  description: APIM Mock API for testing BDS
  version: 1.0.0
servers:
  - url: https://api.ingka.cte.ikeadt.com/apim/hello
    description: APIM Test GCF endpoint sales order attachment bug
paths:
  /apim/test/hello:
    get:
      summary: Returns a greeting message
      responses:
        '200':
          description: A JSON object containing a greeting message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, OpenShift XX !!
