name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build
        run: echo "Building the application..."

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        run: echo "Deploying to dev..."

  deploy-stage:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: staging
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Waiting for approval
        run: echo "Waiting for approval to continue."

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        run: echo "Deploying to staging..."
  
  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-stage
    environment: 
      name: prod
      url: ${{ steps.deploy.outputs.url }}
    if: success()  # Only run if the deploy was successful
    steps:
      - name: Waiting for approval
        run: echo "Waiting for approval to continue."
 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        run: echo "Deploying to prod..."
