name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build
        run: echo "Building the application..."

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build  # Wait for the "build" job to finish
    environment:
      name: dev  # Specify the environment that requires approval
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        run: echo "Deploying to dev..."

  approval-deploy-stage:
    runs-on: ubuntu-latest
    needs: deploy-dev  # Wait for the "deploy" job to finish
    environment: staging  # This environment requires approval before continuing
    if: success()  # Only run if the deploy was successful
    steps:
      - name: Waiting for approval
        run: echo "Waiting for approval to continue."

  deploy-stage:
    runs-on: ubuntu-latest
    needs: approval-deploy-stage  # Wait for the "build" job to finish
    environment:
      name: staging  # Specify the environment that requires approval
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        run: echo "Deploying to staging..."
  
  approval-deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev  # Wait for the "deploy" job to finish
    environment: staging  # This environment requires approval before continuing
    if: success()  # Only run if the deploy was successful
    steps:
      - name: Waiting for approval
        run: echo "Waiting for approval to continue."

  deploy-prod:
    runs-on: ubuntu-latest
    needs: approval-deploy-prod  # Wait for the "build" job to finish
    environment:
      name: staging  # Specify the environment that requires approval
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        run: echo "Deploying to prod..."
